// <auto-generated />
using System;
using GuideAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuideAPI.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250328062651_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuideAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isHidden")
                        .HasColumnType("bit");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(2603),
                            createdBy = 1,
                            departmentName = "Software Development",
                            isHidden = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3024),
                            createdBy = 1,
                            departmentName = "Marketing",
                            isHidden = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3029),
                            createdBy = 1,
                            departmentName = "Admin",
                            isHidden = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3031),
                            createdBy = 1,
                            departmentName = "Human Resources",
                            isHidden = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3052),
                            createdBy = 1,
                            departmentName = "Finance",
                            isHidden = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3054),
                            createdBy = 1,
                            departmentName = "Operations",
                            isHidden = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3055),
                            createdBy = 1,
                            departmentName = "Sales",
                            isHidden = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3056),
                            createdBy = 1,
                            departmentName = "Customer Support",
                            isHidden = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3058),
                            createdBy = 1,
                            departmentName = "Legal",
                            isHidden = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3059),
                            createdBy = 1,
                            departmentName = "Product Management",
                            isHidden = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3060),
                            createdBy = 1,
                            departmentName = "Engineering",
                            isHidden = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3061),
                            createdBy = 1,
                            departmentName = "Business Development",
                            isHidden = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3063),
                            createdBy = 1,
                            departmentName = "Quality Assurance",
                            isHidden = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3064),
                            createdBy = 1,
                            departmentName = "Research & Development",
                            isHidden = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3065),
                            createdBy = 1,
                            departmentName = "IT Support",
                            isHidden = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3066),
                            createdBy = 1,
                            departmentName = "Design",
                            isHidden = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3068),
                            createdBy = 1,
                            departmentName = "Procurement",
                            isHidden = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3069),
                            createdBy = 1,
                            departmentName = "Training",
                            isHidden = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3070),
                            createdBy = 1,
                            departmentName = "Public Relations",
                            isHidden = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 3, 28, 6, 26, 51, 169, DateTimeKind.Unspecified).AddTicks(3071),
                            createdBy = 1,
                            departmentName = "Compliance",
                            isHidden = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
