// <auto-generated />
using System;
using GuideAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuideAPI.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuideAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isHidden")
                        .HasColumnType("bit");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5556),
                            departmentName = "Software Development",
                            isHidden = false
                        },
                        new
                        {
                            Id = 2,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5895),
                            departmentName = "Marketing",
                            isHidden = false
                        },
                        new
                        {
                            Id = 3,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5901),
                            departmentName = "Admin",
                            isHidden = false
                        },
                        new
                        {
                            Id = 4,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5902),
                            departmentName = "Human Resources",
                            isHidden = false
                        },
                        new
                        {
                            Id = 5,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5903),
                            departmentName = "Finance",
                            isHidden = false
                        },
                        new
                        {
                            Id = 6,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5904),
                            departmentName = "Operations",
                            isHidden = false
                        },
                        new
                        {
                            Id = 7,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5906),
                            departmentName = "Sales",
                            isHidden = false
                        },
                        new
                        {
                            Id = 8,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5907),
                            departmentName = "Customer Support",
                            isHidden = false
                        },
                        new
                        {
                            Id = 9,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5908),
                            departmentName = "Legal",
                            isHidden = false
                        },
                        new
                        {
                            Id = 10,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5909),
                            departmentName = "Product Management",
                            isHidden = false
                        },
                        new
                        {
                            Id = 11,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5911),
                            departmentName = "Engineering",
                            isHidden = false
                        },
                        new
                        {
                            Id = 12,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5912),
                            departmentName = "Business Development",
                            isHidden = false
                        },
                        new
                        {
                            Id = 13,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5913),
                            departmentName = "Quality Assurance",
                            isHidden = false
                        },
                        new
                        {
                            Id = 14,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5915),
                            departmentName = "Research & Development",
                            isHidden = false
                        },
                        new
                        {
                            Id = 15,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5916),
                            departmentName = "IT Support",
                            isHidden = false
                        },
                        new
                        {
                            Id = 16,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5917),
                            departmentName = "Design",
                            isHidden = false
                        },
                        new
                        {
                            Id = 17,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5918),
                            departmentName = "Procurement",
                            isHidden = false
                        },
                        new
                        {
                            Id = 18,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5919),
                            departmentName = "Training",
                            isHidden = false
                        },
                        new
                        {
                            Id = 19,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5921),
                            departmentName = "Public Relations",
                            isHidden = false
                        },
                        new
                        {
                            Id = 20,
                            createdBy = 1,
                            createdDate = new DateTime(2025, 3, 26, 2, 35, 41, 111, DateTimeKind.Unspecified).AddTicks(5922),
                            departmentName = "Compliance",
                            isHidden = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
